services:
    tox:
        build:
            context: .
        environment:
            - PIP_INDEX_URL=https://aws:${CODEARTIFACT_AUTH_TOKEN}@eventbrite-shared-353605023268.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/
        depends_on:
            keys:
                condition: service_started
        volumes:
            - keys:/etc/eventbrite/keys
    keys:
        image: 353605023268.dkr.ecr.us-east-1.amazonaws.com/keys-volume:master
        command: ["/usr/bin/tail", "-f", "/dev/null"]
        volumes:
            - "keys:/etc/eventbrite/keys"

volumes:
    keys:
